[package]
name = "rustmove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
lazy_static = "1.4.0"
# term_size = "0.3.2"
walkdir = "2.3.2"
